version: 2
updates:
  # Gradleの依存関係を監視
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "gradle"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dependencies:
        patterns:
          - "*" 