/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sakamotodesu.bittrader;


public class App {

    public static void main(String[] args) throws InterruptedException {
        while (true) {
            BitflyerApi bitflyerApi = new BitflyerApi();
            bitflyerApi.request();
            Thread.sleep(60000);
        }
    }

    public String getGreeting() {
        return "Hello world.";
    }

}
