/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sakamotodesu.bittrader;


public class App {

    public static void main(String[] args) {
        BitflyerApi bitflyerApi = new BitflyerApi();
        bitflyerApi.request();
    }

    public String getGreeting() {
        return "Hello world.";
    }

}
