# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@9.3.5
  aws-ecs: circleci/aws-ecs@1.1.0
  aws-cli: circleci/aws-cli@4.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test
      - run: gradle shadowjar
      - persist_to_workspace:
          root: ~/repo
          paths: build/*
workflows:
  build-and-deploy:
    jobs:
      - build
      - aws-ecr/build_and_push_image:
          requires:
            - build
          repo: ${APP_PREFIX}
          region: ${AWS_DEFAULT_REGION}
          tag: ${CIRCLE_SHA1}
          executor: aws-ecr/default
          account_id: ${AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup:
                region: ${AWS_DEFAULT_REGION}
          attach_workspace: true
          path: .
          dockerfile: ./Dockerfile
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          aws-region: AWS_DEFAULT_REGION
          family: ${APP_PREFIX}-service
          cluster-name: ${APP_PREFIX}-cluster
          container-image-name-updates: container=${APP_PREFIX}-service,tag=${CIRCLE_SHA1}